# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/authorize.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_edit.setInputMask("")
        self.login_edit.setObjectName("login_edit")
        self.horizontalLayout.addWidget(self.login_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pass_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_edit.setObjectName("pass_edit")
        self.verticalLayout.addWidget(self.pass_edit)
        self.show_pass_box = QtWidgets.QCheckBox(self.centralwidget)
        self.show_pass_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.show_pass_box.setObjectName("show_pass_box")
        self.verticalLayout.addWidget(self.show_pass_box, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.auth_button = QtWidgets.QPushButton(self.centralwidget)
        self.auth_button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.auth_button.setObjectName("auth_button")
        self.verticalLayout.addWidget(self.auth_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.label.setText(_translate("MainWindow", "Бархатные холмы"))
        self.login_edit.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.pass_edit.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.show_pass_box.setText(_translate("MainWindow", "Показать пароль"))
        self.auth_button.setText(_translate("MainWindow", "Авторизоваться"))
