# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/capchaDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.capcha_label = QtWidgets.QLabel(Form)
        self.capcha_label.setEnabled(True)
        self.capcha_label.setMinimumSize(QtCore.QSize(380, 59))
        self.capcha_label.setMaximumSize(QtCore.QSize(380, 59))
        self.capcha_label.setBaseSize(QtCore.QSize(500, 500))
        self.capcha_label.setStyleSheet("")
        self.capcha_label.setText("")
        self.capcha_label.setObjectName("capcha_label")
        self.verticalLayout.addWidget(self.capcha_label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.capcha_edit = QtWidgets.QLineEdit(Form)
        self.capcha_edit.setMaxLength(10)
        self.capcha_edit.setObjectName("capcha_edit")
        self.horizontalLayout_2.addWidget(self.capcha_edit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.generate_new_btn = QtWidgets.QPushButton(Form)
        self.generate_new_btn.setObjectName("generate_new_btn")
        self.horizontalLayout.addWidget(self.generate_new_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.confirm_button = QtWidgets.QPushButton(Form)
        self.confirm_button.setObjectName("confirm_button")
        self.verticalLayout_2.addWidget(self.confirm_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ввод капчи"))
        self.label.setText(_translate("Form", "Введите текст с капчи"))
        self.capcha_edit.setPlaceholderText(_translate("Form", "Текст с капчи"))
        self.generate_new_btn.setText(_translate("Form", "Сгенерировать новую"))
        self.confirm_button.setText(_translate("Form", "Подтвердить"))
