# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/createOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 419)
        Form.setMinimumSize(QtCore.QSize(293, 363))
        Form.setMaximumSize(QtCore.QSize(404, 419))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.order_id_edit = QtWidgets.QLineEdit(Form)
        self.order_id_edit.setObjectName("order_num_edit")
        self.horizontalLayout.addWidget(self.order_id_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.info_label = QtWidgets.QLabel(Form)
        self.info_label.setStyleSheet("color: rgb(224, 27, 36);")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.create_order_btn = QtWidgets.QPushButton(Form)
        self.create_order_btn.setObjectName("create_order_btn")
        self.verticalLayout.addWidget(self.create_order_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новый заказ"))
        self.label.setText(_translate("Form", "Номер заказа"))
        self.create_order_btn.setText(_translate("Form", "Сформировать заказ"))
